site_name: The IRIS Cookbook 2e
theme: readthedocs
use_directory_urls: false
theme_dir: extend_theme
extra_css: [extra.css]
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - mdx_math

pages:
    - The IRIS Cookbook 2e:

    - IRIS Modeling Philosophy:

    - Ten-Minute Introduction:

    - Linear Stationary Models:

    - Linear Nonstationary Models:

    - Nonlinear Nonstationary Models:

    - Data Management:

    - Estimation:

    - Model Evaluation:

    - Forecasting:

    - Time Series Models:

    - Reporting:

