site_name: The IRIS Cookbook 2e
theme: readthedocs
use_directory_urls: false
theme_dir: extend_theme
extra_css: [extra.css]
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - mdx_math

pages:
    - The IRIS Cookbook 2e: Index.md

    - IRIS Modeling Philosophy: Philosophy.md

    - Ten-Minute Introduction: Introduction.md

    - Linear Stationary Models: LinearStationary.md

    - Linear Nonstationary Models: LinearNonstationary.md

    - Nonlinear Nonstationary Models: Nonlinear.md

    - Data Management: DataManagement.md

    - Estimation: Estimation.md

    - Model Evaluation: Evaluation.md

    - Forecasting: Forecasting.md

    - Time Series Models: TimeSeriesModels.md

    - Reporting: Reporting.md

